services:
  kafka:
    image: kafka-drr:4.1.0
    container_name: kafka41-default
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CLUSTER_ID: "${KAFKA_CLUSTER_ID:-}"
    volumes:
      - kafka-default-data:/var/lib/kafka/data
      - ./docker/default/server.properties:/etc/kafka/server.properties:ro

volumes:
  kafka-default-data:
